sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql
  username: root
  password: 4815162342aa
  database: flawless-tracker_<%= Rails.env %>


defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

# TODO: would it be cleaner to just monkeypatch rails' database.yml reader?

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  # presumably, we'd erb-echo the production password from /etc/something here.
